# Generated by Django 4.2.20 on 2025-05-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                help_text="Upload the document file (PDF, TXT, DOC, etc.)",
                upload_to="documents/%Y/%m/",
            ),
        ),
    ]
