# Generated by Django 4.2.20 on 2025-05-03 12:10

from django.db import migrations, models
import document_manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0002_alter_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                help_text="Upload the document file (PDF, TXT, DOC, etc.). Max size: 100MB",
                upload_to=document_manager.validators.generate_safe_filename,
                validators=[document_manager.validators.validate_document_file],
            ),
        ),
    ]
