# Generated by Django 4.2.20 on 2025-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0006_alter_processinglog_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding_model",
            field=models.CharField(
                default="Not specified",
                help_text="Model used for embedding generation",
                max_length=50,
            ),
        ),
    ]
