# Generated by Django 4.2.20 on 2025-05-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0007_alter_documentchunk_embedding_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="vector_id",
            field=models.CharField(
                blank=True,
                help_text="ID of this chunk in the vector database",
                max_length=100,
                null=True,
            ),
        ),
    ]
