# Generated by Django 4.2.20 on 2025-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        help_text="Name or description of the document you'd like to see added",
                        max_length=255,
                        verbose_name="Document Name",
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the document (optional)",
                        null=True,
                        verbose_name="Document URL",
                    ),
                ),
                ("votes", models.PositiveIntegerField(default=0)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Requested Document",
                "verbose_name_plural": "Requested Documents",
                "ordering": ["-votes", "-requested_at"],
            },
        ),
    ]
