# Generated by Django 4.2.20 on 2025-05-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name. Leave blank to auto-generate.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="document_ma_slug_9ce3fb_idx"),
                    models.Index(fields=["name"], name="document_ma_name_b135db_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name. Leave blank to auto-generate.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of the document content"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload the document file",
                        upload_to="documents/%Y/%m/",
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="SHA256 hash of the file for integrity checking",
                        max_length=64,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        editable=False, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the uploaded file",
                        max_length=100,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Status of vector database processing",
                        max_length=20,
                    ),
                ),
                (
                    "vector_id",
                    models.CharField(
                        blank=True,
                        help_text="ID reference in the vector database",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="document_manager.tag"
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="ProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("upload_started", "Upload Started"),
                            ("upload_completed", "Upload Completed"),
                            ("processing_started", "Processing Started"),
                            ("chunking_completed", "Chunking Completed"),
                            ("embedding_completed", "Embedding Completed"),
                            ("vectordb_upload_completed", "Vector DB Upload Completed"),
                            ("processing_failed", "Processing Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="document_manager.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "created_at"],
                        name="document_ma_documen_61d64b_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="document_ma_event_t_3e4d88_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(
                        help_text="Order of this chunk in the document"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual text content of this chunk"),
                ),
                (
                    "vector_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of this chunk in the vector database",
                        max_length=100,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-ada-002",
                        help_text="Model used for embedding generation",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="document_manager.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="document_ma_documen_9ed28e_idx",
                    ),
                    models.Index(
                        fields=["vector_id"], name="document_ma_vector__448eca_idx"
                    ),
                ],
                "unique_together": {("document", "chunk_index")},
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["slug"], name="document_ma_slug_7bb2b0_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["processing_status"], name="document_ma_process_58d801_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="document_ma_created_807eb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["file_hash"], name="document_ma_file_ha_2ab043_idx"
            ),
        ),
    ]
