# Generated by Django 4.2.20 on 2025-05-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0003_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
