# Generated by Django 4.2.20 on 2025-05-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0004_document_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
