# Generated by Django 4.2.20 on 2025-05-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0005_alter_document_options_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processinglog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("upload_started", "Upload Started"),
                    ("validation_completed", "Validation Completed"),
                    ("upload_completed", "Upload Completed"),
                    ("text_extraction_started", "Text Extraction Started"),
                    ("text_extraction_completed", "Text Extraction Completed"),
                    ("processing_started", "Processing Started"),
                    ("metadata_extraction_completed", "Metadata Extraction Completed"),
                    ("chunking_started", "Chunking Started"),
                    ("chunking_completed", "Chunking Completed"),
                    ("embedding_started", "Embedding Started"),
                    ("embedding_completed", "Embedding Completed"),
                    ("vectordb_upload_started", "Vector DB Upload Started"),
                    ("vectordb_upload_completed", "Vector DB Upload Completed"),
                    ("analysis_started", "Analysis Started"),
                    ("entity_extraction_completed", "Entity Extraction Completed"),
                    ("summary_generation_completed", "Summary Generation Completed"),
                    ("analysis_completed", "Analysis Completed"),
                    ("document_activated", "Document Activated"),
                    ("document_deactivated", "Document Deactivated"),
                    ("document_updated", "Document Updated"),
                    ("reprocessing_started", "Reprocessing Started"),
                    ("reindexing_completed", "Reindexing Completed"),
                    ("processing_failed", "Processing Failed"),
                    ("validation_failed", "Validation Failed"),
                    ("chunking_failed", "Chunking Failed"),
                    ("embedding_failed", "Embedding Failed"),
                    ("vectordb_upload_failed", "Vector DB Upload Failed"),
                    ("analysis_failed", "Analysis Failed"),
                ],
                max_length=50,
            ),
        ),
    ]
