# Generated by Django 4.2.20 on 2025-06-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0008_alter_documentchunk_vector_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="chunk_type",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="page_end",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="page_start",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
