# Generated by Django 4.2.20 on 2025-06-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "document_manager",
            "0009_documentchunk_chunk_type_documentchunk_metadata_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
