# Generated by Django 4.2.20 on 2025-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0010_document_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="contents_page",
            field=models.TextField(
                blank=True,
                help_text="Formatted table of contents with headlines and page ranges",
            ),
        ),
    ]
