# Generated by Django 4.2.20 on 2025-06-10 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0011_document_contents_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("document", "Document Summary"),
                            ("section", "Section Summary"),
                        ],
                        help_text="Type of summary: document-level or section-level",
                        max_length=20,
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the section (e.g., 'Eligibility Requirements'). Null for document summaries.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "page_start",
                    models.IntegerField(
                        blank=True,
                        help_text="First page of the section (1-indexed). Null for document summaries.",
                        null=True,
                    ),
                ),
                (
                    "page_end",
                    models.IntegerField(
                        blank=True,
                        help_text="Last page of the section (1-indexed). Null for document summaries.",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual summary text content"),
                ),
                (
                    "vector_id",
                    models.CharField(
                        blank=True,
                        help_text="ID reference in the vector database (Qdrant)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        blank=True,
                        help_text="Model used to generate embeddings for this summary",
                        max_length=100,
                    ),
                ),
                (
                    "processing_version",
                    models.CharField(
                        blank=True,
                        help_text="Version of the processing pipeline used to generate this summary",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document this summary belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="document_manager.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Summary",
                "verbose_name_plural": "Document Summaries",
                "ordering": ["summary_type", "page_start"],
                "indexes": [
                    models.Index(
                        fields=["document", "summary_type"],
                        name="document_ma_documen_838faf_idx",
                    ),
                    models.Index(
                        fields=["document", "page_start"],
                        name="document_ma_documen_bc5f57_idx",
                    ),
                    models.Index(
                        fields=["vector_id"], name="document_ma_vector__e83bc7_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="document_ma_created_f74a38_idx"
                    ),
                ],
            },
        ),
    ]
