# Generated by Django 4.2.20 on 2025-06-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0012_documentsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsummary",
            name="summarisation_model",
            field=models.CharField(
                blank=True, help_text="Model used to generate summaries", max_length=100
            ),
        ),
    ]
