# Generated by Django 4.2.20 on 2025-06-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0013_documentsummary_summarisation_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentsummary",
            options={
                "ordering": ["summary_type", "section_name"],
                "verbose_name": "Document Summary",
                "verbose_name_plural": "Document Summaries",
            },
        ),
        migrations.RemoveIndex(
            model_name="documentsummary", name="document_ma_documen_bc5f57_idx",
        ),
        migrations.RemoveField(model_name="documentsummary", name="page_end",),
        migrations.RemoveField(model_name="documentsummary", name="page_start",),
        migrations.RemoveField(
            model_name="documentsummary", name="summarisation_model",
        ),
    ]
