# Generated by Django 4.2.20 on 2025-06-14 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0015_documentsummary_summarisation_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="embeded_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 14, 17, 11, 19, 114320, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentsummary",
            name="embeded_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 14, 17, 11, 25, 264712, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
