# Generated by Django 4.2.20 on 2025-06-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "document_manager",
            "0016_documentchunk_embeded_at_documentsummary_embeded_at",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentchunk", old_name="embeded_at", new_name="embedded_at",
        ),
        migrations.RenameField(
            model_name="documentsummary", old_name="embeded_at", new_name="embedded_at",
        ),
    ]
