# Generated by Django 4.2.20 on 2025-07-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "document_manager",
            "0017_rename_embeded_at_documentchunk_embedded_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="processinglog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("upload_started", "Upload Started"),
                    ("validation_completed", "Validation Completed"),
                    ("upload_completed", "Upload Completed"),
                    ("text_extraction_started", "Text Extraction Started"),
                    ("text_extraction_completed", "Text Extraction Completed"),
                    ("processing_started", "Processing Started"),
                    ("metadata_extraction_completed", "Metadata Extraction Completed"),
                    ("chunking_started", "Chunking Started"),
                    ("chunking_completed", "Chunking Completed"),
                    ("embedding_started", "Embedding Started"),
                    ("embedding_completed", "Embedding Completed"),
                    ("vectordb_upload_started", "Vector DB Upload Started"),
                    ("vectordb_upload_completed", "Vector DB Upload Completed"),
                    ("summarisation_started", "Summarisation Started"),
                    ("summarisation_completed", "Summarisation Completed"),
                    ("document_activated", "Document Activated"),
                    ("document_deactivated", "Document Deactivated"),
                    ("document_updated", "Document Updated"),
                    ("reprocessing_started", "Reprocessing Started"),
                    ("reindexing_completed", "Reindexing Completed"),
                    ("processing_failed", "Processing Failed"),
                    ("validation_failed", "Validation Failed"),
                    ("chunking_failed", "Chunking Failed"),
                    ("summarisation_failed", "Summarisation Failed"),
                    ("embedding_failed", "Embedding Failed"),
                    ("vectordb_upload_failed", "Vector DB Upload Failed"),
                ],
                max_length=50,
            ),
        ),
    ]
