# Generated by Django 4.2.20 on 2025-07-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0018_alter_processinglog_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
