# Generated by Django 4.2.20 on 2025-07-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0019_alter_document_metadata"),
    ]

    operations = [
        # First, remove the ManyToMany field (this drops the junction table)
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        
        # Then, delete the Tag model entirely
        migrations.DeleteModel(
            name='Tag',
        ),
    ]