# Generated by Django 4.2.20 on 2025-07-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0020_auto_20250704_1635"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name. Leave blank to auto-generate.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="document_ma_slug_9ce3fb_idx"),
                    models.Index(fields=["name"], name="document_ma_name_b135db_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="document_manager.tag"
            ),
        ),
    ]
