# Generated by Django 4.2.20 on 2025-07-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0021_tag_document_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
