# Generated by Django 4.2.20 on 2025-07-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0022_alter_documentchunk_embedded_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentchunk",
            options={
                "ordering": ["document", "chunk_index"],
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
            },
        ),
        migrations.AlterField(
            model_name="documentsummary",
            name="embedded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
