# Generated by Django 4.2.20 on 2025-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0023_alter_documentchunk_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="collection_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
