# Generated by Django 4.2.20 on 2025-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_manager", "0024_document_collection_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="chunking_model",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="embedding_model",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="estimated_cost_of_processing",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="summarising_model",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
